export const sessions = [
  {
    id: 1,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 2,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 3,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 4,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 5,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 6,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 7,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 8,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 9,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
  {
    id: 10,
    date: "Tue-Nov 10",
    time: "4:00PM - 6:00PM",
    subjects: ["Science Lv.1", "Math Lv.1"],
    location: "Bloor Collegiate Institute",
  },
];
